# Generated by Django 2.2.19 on 2022-07-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220713_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='null'),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='Imps', max_length=200),
        ),
    ]
