# Generated by Django 2.2.19 on 2022-09-03 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0017_auto_20220825_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(default=3, help_text='Создатель группы', on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Заголовок поста', help_text='Напишите здесь заголовок поста', max_length=140, verbose_name='Заголовок поста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=0, help_text='Количество голосов за пост', verbose_name='Голоса'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(help_text='Пост, за который проголосовали', on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to='posts.Post', verbose_name='Пост')),
                ('voter', models.ForeignKey(help_text='Польгователь, проголосовавший за пост', on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL, verbose_name='Голосующий')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
            },
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'post'), name='unique_vote'),
        ),
    ]
