# Generated by Django 2.2.19 on 2022-09-04 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20220904_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.BigIntegerField(default='0', help_text='Счетчик лайков', verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(help_text='Пользователи, лайкнувшие пост', related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
