# Generated by Django 2.2.19 on 2022-09-04 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20220904_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, help_text='Пользователи, лайкнувшие пост', related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
